"""identity and membership tables

Revision ID: 54db183c134c
Revises:
Create Date: 2026-07-22 22:25:35.904071
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "54db183c134c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Enable pgvector (used by knowledge_embeddings from Week 1 Wednesday onward).
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("customer", "admin", name="userrole", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("active", "suspended", name="accountstatus", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("display_name", sa.String(length=120), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "memberships",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "package",
            sa.Enum(
                "none", "entry_49", "coaching_199", name="package", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column(
            "access_state",
            sa.Enum(
                "inactive",
                "active",
                "expired",
                "paused",
                name="accessstate",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "ai_level",
            sa.Enum(
                "none", "basic_chat", "energy_guide", name="ailevel", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column(
            "renewal_status",
            sa.Enum("none", "auto", "manual", name="renewalstatus", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_memberships_user_id"), "memberships", ["user_id"], unique=True)
    op.create_table(
        "payment_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum(
                "stripe", "paypal", "crypto", name="paymentprovider", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column(
            "package",
            sa.Enum(
                "none", "entry_49", "coaching_199", name="package", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "succeeded",
                "failed",
                "refunded",
                name="paymentstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("tx_hash", sa.String(length=120), nullable=True),
        sa.Column("chain", sa.String(length=30), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payment_records_external_id"), "payment_records", ["external_id"], unique=False
    )
    op.create_index(
        op.f("ix_payment_records_tx_hash"), "payment_records", ["tx_hash"], unique=False
    )
    op.create_index(
        op.f("ix_payment_records_user_id"), "payment_records", ["user_id"], unique=False
    )
    op.create_table(
        "user_identities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum("email", "wallet", name="identityprovider", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("identifier", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "identifier", name="uq_identity_provider_identifier"),
    )
    op.create_index(
        op.f("ix_user_identities_user_id"), "user_identities", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_identities_user_id"), table_name="user_identities")
    op.drop_table("user_identities")
    op.drop_index(op.f("ix_payment_records_user_id"), table_name="payment_records")
    op.drop_index(op.f("ix_payment_records_tx_hash"), table_name="payment_records")
    op.drop_index(op.f("ix_payment_records_external_id"), table_name="payment_records")
    op.drop_table("payment_records")
    op.drop_index(op.f("ix_memberships_user_id"), table_name="memberships")
    op.drop_table("memberships")
    op.drop_table("users")
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS vector")
