"""knowledge inbox

Revision ID: c794e8082352
Revises: af6df0caea16
Create Date: 2026-07-29 08:32:20.326771
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c794e8082352"
down_revision: Union[str, None] = "af6df0caea16"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "knowledge_inbox",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "new", "promoted", "archived", name="inboxstatus", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("promoted_entry_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["promoted_entry_id"], ["knowledge_entries.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_knowledge_inbox_status"), "knowledge_inbox", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_knowledge_inbox_status"), table_name="knowledge_inbox")
    op.drop_table("knowledge_inbox")
    # ### end Alembic commands ###
